language: php
php:
  - 5.4
  - 7
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar"
  - php -S 127.0.0.1:8000 &
script:
  - "java -jar selenium-server-standalone-2.42.1.jar -htmlSuite *firefox http://127.0.0.1:8000/ /home/travis/build/commercefactory/005-paypal-express-checkout-php/tests/suite.html ./result"
  - "php -r 'echo strip_tags(file_get_contents(\"result\"));'"
